### PR TITLE
Unlock nokogiri update to 1.9.1

### PR DESCRIPTION
**Pull request by Jesterovskiy**

### CODE REVIEW

**Comment by Jesterovskiy** [comment]
@blethier @aurelien-reeves @vincent-psarga Can somebody review my PR? Thanks)

**Comment by cbliard** [comment]
Sorry, we missed your pull request. It waited far too long.

I would prefer having the nokogiri dependency being `~> 1.8` rather than `>= 1.8` so that we prevent usage of a future 2.0 version which could break things.

It looks like there are other gem updates. I think it's ok. We will check that.

**Comment by Jesterovskiy** [comment]
@cbliard thanks, waiting for check)

**Comment by cbliard** [comment]
@Jesterovskiy Yes, we checked and everything is ok for us. Can you change the nokogiri dependency from `>= 1.8` to `~> 1.8`, then I'll be happy to merge.

**Comment by Jesterovskiy** [comment]
@cbliard done and thanks

**Comment by cbliard** [comment]
Thanks!

**Pull request merged**
