### PR TITLE
Behat integration

### PR DESCRIPTION
**Pull request by tikolakin**
This change is for reducing code duplication
So it's just much easier to inject all hiptest's actionwords to any context.

### CODE REVIEW

**Comment by tikolakin** [comment]
Hi @vincent-psarga is there a way to make template be more configurable? for ex. to set a namespace?
Thanks

**Comment by tikolakin** [comment]
or even much simpler way to get actionwords into context file is to put actionwords into the interface and to implement the interface with a context file, this way looks more solid.
in order to avoid

```
Ambiguous match of "I am on "blog" page":
      to `/^I am on "(.*)" page$/` from Feature\Context\Context::iAmOnP1Page()
      to `I am on :specific_title page` from Feature\Context/Context::iAmOnP1Page()
```

the implemented step definition should override method like

```
  /**
     *
     * @overridden @Given I am on :specific_title page
     */
    public function iAmOnP1Page($specificTitle)
    {
        $this->getPage(specificTitle)->open();
    }
```

I personally like second this idea.

In the pull request I'm trying to get rid of generation a context file, the context is useless.

**Comment by vincent-psarga** [comment]
Hi Tiko,

Thanks for your contribution. That said there's one thing I don't understand in it. With your solution (if I understand correctly), you would implement the content of the action words inside the steps definition class instead of the action words class right ?

The other thing I'm not fan of is that, with your solution, there is no default implementation generated. For example, let's consider that you refactor two action words in a single one in Hiptest (let's say action words "login" and "open settings" are called by an action words "login and open settings") hippest-publisher will not generate the default implementation as it would do normally.

**Comment by tikolakin** [comment]
Hi @vincent-psarga 
1. yes. we do have a really big test codebase and that is why it's just ok to keep framework specific implementation rather than follow a third part service architecture.
So then we inject hiptest actionwords into the framework and allow framework to get updates that are happening on UI of hiptest, so keep things in sync.
2. what do you mean under "default implementation"?
From what I understand it's when you merge first and second actionwords into single third actionword and then import it via hiptest publisher - you will get three methods in Actionwords class. Given that you will need to override new (third) action word in a mine context that extends Actionwords class.
This third actionword will look like:
```
file: Actionwords.php

function first(){
  throw new Pending();
}

function second(){
  throw new Pending();
}

function third(){
   throw new Pending();
}
```

```

class AcmeContext extends Actionwords {
  function third(){
    $this->first();
    $this->second();
  }
}
```

**Comment by tikolakin** [comment]
Vincent, sorry that I didn't test this case, scenarios inline is not working to me atm, I can't use this feature for the time being

**Comment by vincent-psarga** [comment]
Hi Tiko,

One solution I'm thinking of that would not impact too much customers that already use the Behat export would be to define a new "language" in Hiptest-publisher to use your solution.

Basically, if you use --language=behat, it will generate the scripts as they currently generate, but adding the option --framework=abstrat (well, the framework option name is not perfect I know) would use your code.

Would that be a good solution for you ?

**Comment by vincent-psarga** [comment]
I'll send you some links on how to handle that (maybe via a PR on your repo that you could then merge, then PR it back to here :) )

**Comment by tikolakin** [comment]
well, probably specs will help me https://github.com/hiptest/hiptest-publisher/blob/master/spec/template_finder_spec.rb
@vincent-psarga I think that the correct way for behat is 
--language=php --framework=behat (--framework=behat_abstract)
is it possible?

**Comment by vincent-psarga** [comment]
Well, the idea is to create a subfolder in lib/templates/behat called "abstract"

All the templates you have modified should be copied to this new folder then reverted in the original folder.

In lib/config, create a file called behat-abstract with this content:

```
[_common]
indentation = '  '
fallback_template = 'empty'

[features]
indentation = '  '
node_name = folders
template_dirs = gherkin, common
named_filename = '%s.feature'
filename_convention = 'underscore'

[step_definitions]
node_name = actionwords
template_dirs = behat/abstract, behat, php, common
filename = 'FeatureContext.php'
naming_convention = 'camelize'
call_prefix = 'self.actionwords'

[actionwords]
template_dirs = behat/abstract, php, common
filename = 'Actionwords.php'
naming_convention = 'camel_case'
call_prefix = '$this'
```

With that, you should be able to do: hiptest-publisher -c <config file> -l beat -f abstract

For the tests, in spec/render/behat_spec.rb, add at the end of the file:

```
describe 'Behat rendering' do
  it_behaves_like 'a BDD renderer' do
    let(:language) {'behat'}

    let(:rendered_actionwords) {
      // the expected output
   }
  end
end
```

**Comment by tikolakin** [comment]
hi @vincent-psarga , I left only documentation how to override the behat template to have actionwords in abstract class, as far as it's easily possible with overriding template

**Pull request merged**
