### PR TITLE
Add filename_pattern option

### PR DESCRIPTION
**Pull request by mhfrantz**
https://github.com/hiptest/hiptest-publisher/issues/27

### CODE REVIEW

**Comment by mhfrantz** [comment]
I admit that the test that I added is a bit heavy-handed because it is a full integration test.  If you'd rather have a more directed unit test, I can give it a try, but haven't learned my way around that part of the code yet.

**Comment by mhfrantz** [comment]
@vincent-psarga Let me know if you need anything on this one.

**Comment by vincent-psarga** [comment]
Thanks a lot for the request, that looks really cool :)
We've discussed it briefly with @cbliard and we'll release that soon :)

**Comment by vincent-psarga** [comment]
Hi Matt,

Version 0.13.2 ships the option you added. Sorry about the long time for releasing, I forgot to do it and I was expecting some changes to be done to the publisher last week.

Best regards,
Vincent

**Pull request merged**
