### PR TITLE
Support Docker developer environment

### PR DESCRIPTION
**Pull request by mhfrantz**
This is ready.  Let me know if I should rebase to remove the log files backtracking.

### CODE REVIEW

**Comment by mhfrantz** [comment]
Since my email, I've made progress, as shown in the subsequent commits.  The only test that fails for me now (in Docker) is `utils`.  I remember this one being tricky because it has to do with stdout, and the possibility of buffering that differs in Docker versus the host environment.
```
  1) Hiptest publisher utils show_status_message is a tty sends a message on STDOUT with brackets before
     Failure/Error: expect(STDOUT).to have_received(:print).with("[ ] My message\r\e[1A\n").once
       (#<IO:0x005622a3d31bb8>).print("[ ] My message\r\e[1A\n")
           expected: 1 time with arguments: ("[ ] My message\r\e[1A\n")
           received: 0 times
     # ./spec/utils_spec.rb:19:in `block (4 levels) in <top (required)>'
```

**Comment by mhfrantz** [comment]
Ah, it turns out that the problem with the test failure was because I am tying stdout and stderr together in the Makefile (`2>&1`), so the error output ends up on stdout instead of stderr, as the test assumes.

**Comment by mhfrantz** [comment]
@vincent-psarga : Do you need me to do anything to this PR?

**Comment by vincent-psarga** [comment]
What I really need most is a bit of free time to take a deep look before accepting the request (but good news for you, most of my time is occupied by integrating the triple quoted strings in Hiptest ;) )

**Comment by vincent-psarga** [comment]
Hi Matt,

Finally found some time to look a bit deeper at the PR and it's really cool :)

I will just do a few changes if you don't mind:
 - host the docker image on hiptest/hiptest-publisher
 - update the script bin/hiptest-publisher.sh to bin/hiptest-publisher-docker so it's clearer that it uses Docker

**Comment by mhfrantz** [comment]
Yes, of course.  Thanks.

**Comment by cbliard** [comment]
Vincent's suggestions are now active, and I configured [hiptest/hiptest-publisher](https://hub.docker.com/r/hiptest/hiptest-publisher/) to be an automated docker build.

Thank you Matt! This is really cool to be able to use hiptest-publisher without installing ruby.

**Pull request merged**
