### PR TITLE
Align /lib/templates/robotframework to naming convention for keywords…

### PR DESCRIPTION
**Pull request by ndo-topps**
… (i.e. normalize_with_spaces) and files (i.e. Camelize.robot) with language. Replaced tabs with 4 spaces for consistent spacing.

### CODE REVIEW

**Comment by vincent-psarga** [comment]
Hi,

Thanks for your contribution. That said there's a small problem (except the tests failing) with changing the way the action words are named.
The problem here is for users who already have exported action words using the "underscore" naming convention, then their tests are going to fail (as the keywords will not be recognised, unless you tell me otherwise, I'm not a Robot framework expert. If it can match the keywords even if the name do not exactly match, that could work).

Best regards,
Vincent

**Comment by vincent-psarga** [comment]
Ho one thing is forgot about the naming convention.
Hiptest-publisher allows to override templates for customising the export. In your case, one possibility would be to override the templates for a call (https://github.com/hiptest/hiptest-publisher/blob/master/lib/templates/robotframework/call.hbs) and for an action word (https://github.com/hiptest/hiptest-publisher/blob/master/lib/templates/robotframework/actionword.hbs) so it uses normalize_with_spaces instead of underscore for your project only (and so not impacting users who have already implemented their keywords).

**Comment by ndo-topps** [comment]
Thanks, Vince. I understand this change may break existing customers using RobotFramework without knowing how many exactly. Personally, I'm doubtful anyone committed to Hiptest and RobotFramework can easily automate at any level of coupling especially strong coupling since none for the builtin libraries would work directly. For example, 'Click element' would not work out of the box since hiptest-publisher exports it as click_element: http://robotframework.org/Selenium2Library/doc/Selenium2Library.html. 

I also need to override /lib/config/robotframework.conf for the naming convention of the files. Would you allow this capability in hiptest-publisher?

**Comment by vincent-psarga** [comment]
Hi Neil,

The simplest way to handle this I think will be some emailing to our customers who already have done some exports with hiptest publisher and see if those changes will be to hard to handle (or if they consider the current export as being not "robot framework like" enough and they will be glad to have them).

I'll do some emailing today and we'll see the feedback :)

**Pull request closed without merging**
