### PR TITLE
Support for Cucumber TypeScript

### PR DESCRIPTION
**Pull request by tenpaiyomi**
Adds in support for Cucumber TypeScript.  Only includes bare essentials for imports (`cucumber` and `actionwords`) to not make assumptions about any other libraries or frameworks the user may be wanting to make use of.

Includes rspec tests as well.

### CODE REVIEW

**Comment by vincent-psarga** [comment]
Hey,

Thanks a lot for the work on supporting this new framework. I'll run some tests with it on one of our classical samples and merge that PR is everything goes fine :)

Cheers,
Vincent

**Comment by vincent-psarga** [comment]
Hi,

So I've done some tests and found a few issues. You can find the repo for which I did the checks here: https://github.com/hiptest/hps-cucumber-typescript

Basically, I had to change a few things in the code:

```
diff --git a/lib/hiptest-publisher/options_parser.rb b/lib/hiptest-publisher/options_parser.rb
index c17fa1f..afef93a 100644
--- a/lib/hiptest-publisher/options_parser.rb
+++ b/lib/hiptest-publisher/options_parser.rb
@@ -188,7 +188,7 @@ class OptionsParser
 
     {
       'Ruby' => ['Rspec', 'MiniTest'],
-      'Cucumber' => ['Ruby', 'Java', 'Javascript', 'Groovy'],
+      'Cucumber' => ['Ruby', 'Java', 'Javascript', 'Groovy', 'TypeScript'],
       'Java' => ['JUnit', 'Test NG', 'Espresso'],
       'Python' => ['Unittest'],
       'Robot Framework' => [''],
diff --git a/lib/templates/typescript/parameter.hbs b/lib/templates/typescript/parameter.hbs
index 7c6d516..df343bf 100755
--- a/lib/templates/typescript/parameter.hbs
+++ b/lib/templates/typescript/parameter.hbs
@@ -1 +1 @@
-{{{ underscore rendered_children.name }}}{{#if has_default_value?}} = "{{{ rendered_children.default }}}"{{else}}: {{{ node.type }}}{{/if}}
\ No newline at end of file
+{{{ underscore rendered_children.name }}}{{#if has_default_value?}} = {{{ rendered_children.default }}}{{else}}: {{{ node.type }}}{{/if}}
\ No newline at end of file
diff --git a/spec/render/cucumber_spec.rb b/spec/render/cucumber_spec.rb
index 4ce545b..32ef69f 100644
--- a/spec/render/cucumber_spec.rb
+++ b/spec/render/cucumber_spec.rb
@@ -320,12 +320,12 @@ describe 'Cucumber/TypeScript rendering' do
     let(:framework) {'typescript'}
 
     let(:rendered_free_texted_actionword) {[
-      'theFollowingUsersAreAvailable(__free_text = "\'\'") {',
+      'theFollowingUsersAreAvailable(__free_text = \'\') {',
       '',
       '}'].join("\n")}
 
      let(:rendered_datatabled_actionword) {[
-       'theFollowingUsersAreAvailable(__datatable = "\'\'") {',
+       'theFollowingUsersAreAvailable(__datatable = \'\') {',
        '',
        '}'].join("\n")}
```

The first fix is just for help.
The second one (in parameter.hbs) ensure that the generated code compiles when there are defaults values (otherwise it generates four doubles quotes when the default value is an empty string).

Other than that, with the code generated, hen I run the tests, I get an error:

```
features/step_definitions.ts:2:29 - error TS2307: Cannot find module 'actionwords'.

2 import { ActionWords } from 'actionwords';
```

I tried to fix that by changing using the import to "import { ActionWords } from './actionwords';", but when I do that, I'm getting other errors like this:

```
features/step_definitions.ts:12:17 - error TS2339: Property 'iStartTheCoffeeMachineUsingLanguageLang' does not exist on type 'typeof ActionWords'.

12     ActionWords.iStartTheCoffeeMachineUsingLanguageLang(lang);
```

This is certainly due to misconfiguration in my project (I don't do much Typescript to be frank).

I keep investigating and keeping you informed :)

**Comment by vincent-psarga** [comment]
That's exactly what I did after ;)
I've overrides the templates in https://github.com/hiptest/hps-cucumber-typescript so this way the steps definitions can be autogenerated (and the code only written in Actionwords.ts)

I need to run now but I keep working on that ;)

**Comment by vincent-psarga** [comment]
Hello,

So I've made some other tests/changes in the templates you proposed which can be found in this repo: https://github.com/hiptest/hps-cucumber-typescript (under the templates directory where I've overrides your templates)

Those changes allow a few things:
 - we now call an instance of ActionWords instead of class method (which where not working previously)
 - the TableDefinition type is now handled correctly

If those changes seem good for you, I think we can work together on getting this PR merged (so either you update your templates based on the changes I propose or otherwise, I merge your PR update the templates later on, as you prefer).

Best regards,
Vincent

**Comment by tenpaiyomi** [comment]
I'll make the requested changes and update the PR.  Thank you very much!

**Comment by vincent-psarga** [comment]
Thanks for the changes. Before merging/relasing, I'd like to have some extra changes integrated to ensure that we use an instance of the ActionWords class instead of calling class method like in your implementation.

Those templates handle that:
 - https://github.com/hiptest/hps-cucumber-typescript/blob/master/templates/cucumber/typescript/actionwords.hbs - declare the actionWords instance
 - https://github.com/hiptest/hps-cucumber-typescript/blob/master/templates/cucumber/typescript/_before_hook.hbs - initialise the actionwords instance in the before hook
 - https://github.com/hiptest/hps-cucumber-typescript/blob/master/templates/cucumber/typescript/actionword.hbs - use the instance

And there's also some templates to update in lib/templates/typescript show here: https://github.com/hiptest/hps-cucumber-typescript/tree/master/templates/typescript

This is a major change to your original implementation, so I'd prefer to have your opinion on that too if you don't mind ;)

Best regards,
Vincent

**Comment by tenpaiyomi** [comment]
Looking over the changes now, they make sense.  I was initially thinking about tossing out the thought of making the class methods static so that a class instance would not need to be instantiated, but figured the benefit of that would negate potential benefits of allowing the user to modify the constructor of the class and passing in whatever potential variables they may want to use across the instance of the class.

I'll go ahead and do the needful now.

**Comment by tenpaiyomi** [comment]
A quick question, is there a reason you do this:

```
let actionWords : ActionWords;

Before(async () => {
actionWords = new ActionWords();
});
```

Instead of just:

```
const actionWords = new ActionWords();
```

**Comment by tenpaiyomi** [comment]
Actually, disregard that.  Looking over everything else, it looks like it's generally the norm to do the assignment within the before block, so I can understand why now.

**Comment by tenpaiyomi** [comment]
@vincent-psarga Changes made, spec updated to reflect the new changes

**Comment by vincent-psarga** [comment]
Yes generally I prefer doing the instance's creation in the before() block to start every test with a fresh instance, that generally avoids having data share across multiple scenarios and getting unstable tests :) (I've had the issue with another framework before)

**Comment by vincent-psarga** [comment]
I just tried it, work great :)
It'll be released in the coming hours ;)

**Pull request merged**
