### PR TITLE
Added support for CodeceptJS testing framework

### PR DESCRIPTION
**Pull request by DavertMik**
[CodeceptJS](http://codecept.io) is end 2 end testing framework for NodeJS. It provides [complete BDD support](https://codecept.io/bdd) similar to Cucumber.

We are using CodeceptJS with HipTest to sync up feature files and push back reports. Current implementation is mostly similar to Cucumber/JavaScript with minor differences.

### CODE REVIEW

**Comment by vincent-psarga** [comment]
Thanks for the PR, I'm trying it and give you a feedback ASAP :)

**Comment by vincent-psarga** [comment]
I've tried out your export with our classical Coffee machine project and it works fine (https://github.com/hiptest/hps-javascript-codeceptjs). Well, the tests run, they fail but that looks more like a Puppeteer missconfig issue than the code you've written.

On little thing before merging, I've add to override a bit the action words.hbs file (https://github.com/hiptest/hps-javascript-codeceptjs/blob/master/templates/javascript/codeceptjs/actionwords.hbs) so the actionwords object was reinitialised before each test. I'm not familiar enough with Codecept but that's generally a good practice to avoid tests failing (or working :D ) due to a bad reinitialising.

Would you consider adding that to your PR and then I can merge ? (or convince me that it's the way it should be done with Codecept, that works for me too :D )

**Comment by DavertMik** [comment]
Thanks, @vincent-psarga I updated the request as you asked. (copy pasted your code :smile: )
The produced code looks fine from my side.

**Comment by DavertMik** [comment]
@vincent-psarga :up:

**Comment by vincent-psarga** [comment]
Hi @davertmik,

Thank you for updating the PR. I'm on holiday right now, I'll have a look in two weeks when I'm back if that's ok for you :)

**Comment by vincent-psarga** [comment]
Thanks again for your contribution @DavertMik :)
I'll do the new release of hiptest-publisher as soon as possible with your support for Codecept as soon as possible.

**Pull request merged**
